%% Módulo 03: CQRS con proyecciones via eventos
flowchart LR
    UI[UI/API]
    subgraph WRITE["Write Side (Commands)"]
        CMD[Command Handler]
        AR[Aggregate Root]
        EVT[(Event Store<br/>Kafka/Streams)]
        CMD --> AR
        AR --> EVT
    end

    subgraph READ["Read Side (Queries)"]
        P1[(Proyección: Vista órdenes)]
        P2[(Proyección: Vista cliente)]
        P3[(Elasticsearch/Search)]
        Q[Query Handler]
    end

    EVT --> P1
    EVT --> P2
    EVT --> P3
    P1 --> Q
    P2 --> Q
    P3 --> Q
    UI --> Q
    UI --> CMD

    classDef write fill:#D97706,stroke:#fff,color:#fff;
    classDef read fill:#059669,stroke:#fff,color:#fff;
    classDef store fill:#0E8A5F,stroke:#fff,color:#fff;
    class CMD,AR write;
    class Q read;
    class EVT store;
    class P1,P2,P3 read;