%% Módulo 05: Particionamiento y single-table en DynamoDB
flowchart TD
    APP["Aplicación / Lambda"]
    PK["Partition Key (hash)"] --> A1["Partición 1"] 
    PK --> A2["Partición 2"]
    PK --> A3["Partición 3"]
    PK --> H["HOT PARTITION 🔥<br/>(hot key) <br/>Throttle local"]

    subgraph S["Single-Table / Adjacency List"]
        C1["PK: CUSTOMER#1<br/>SK: ORDER#100, ORDER#101, PROFILE#"]
        C2["PK: ORDER#100<br/>SK: PRODUCT#p9, PAYMENT#200"]
    end

    APP --> PK
    APP -->|"Query(PK=customer, SK begins_with ORDER#)"| S

    classDef part fill:#FF9900,stroke:#232F3E,color:#fff;
    classDef hot fill:#D0021B,stroke:#fff,color:#fff;
    classDef single fill:#0E8A5F,stroke:#fff,color:#fff;
    class A1,A2,A3 part;
    class H hot;
    class S,C1,C2 single;